version: "3.8"

networks:
  default:
    driver: bridge

services:

  postgres:
    container_name: postgresql
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  service:
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5053:5053"
    build: .
    image: shaffra-service:latest
    env_file:
      - .env
volumes:
  postgres-data: